#!/usr/bin/env python3
"""Generate/check Codex adapters for the Claude Code capability surface.

Canonical capability definitions live under `.claude/`. Codex discovers a
different set of project-local surfaces:

- `.agents/skills/*/SKILL.md` for repo skills.
- `.codex/agents/*.toml` for custom subagents.

This script keeps those adapters mechanical so the template can support both
Claude Code and Codex without maintaining two hand-written copies.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _frontmatter_and_body(path: Path) -> tuple[dict[str, str], str, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError(f"missing frontmatter: {path.relative_to(REPO)}")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "\t", "-")):
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()
    return fields, text[match.end() :], text


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"""')
    return f'"""\n{escaped.rstrip()}\n"""'


def _sandbox_for_tools(tools: str) -> str:
    tool_set = {part.strip() for part in tools.split(",") if part.strip()}
    if {"Edit", "Write", "NotebookEdit"} & tool_set:
        return "workspace-write"
    return "read-only"


def _agent_adapter(path: Path) -> tuple[Path, str]:
    fields, body, _ = _frontmatter_and_body(path)
    name = fields.get("name")
    description = fields.get("description")
    if not name or not description:
        raise ValueError(f"agent frontmatter lacks name/description: {path.relative_to(REPO)}")

    tools = fields.get("tools", "")
    model = fields.get("model", "")
    model_note = ""
    if model and model != "inherit":
        model_note = (
            f"\nOriginal Claude Code model hint: `{model}`. Codex leaves the concrete "
            "model unset in this project adapter; choose the closest low-cost/appropriate "
            "model at spawn time if this hint matters.\n"
        )

    instructions = f"""Codex adapter for `{path.relative_to(REPO)}`.

Canonical source: `{path.relative_to(REPO)}`. Do not edit this TOML by hand; edit the
canonical Claude Code agent and run `python scripts/sync-codex-adapters.py`.

Original Claude Code tool list: `{tools or "not declared"}`.
Codex custom-agent TOML does not enforce the exact Claude tool list, so treat that list
as a behavioral boundary. Stay within it voluntarily; if the task needs more capability,
stop and escalate to the parent agent.
{model_note}
---

{body.rstrip()}
"""

    content = "\n".join(
        [
            "# Generated by scripts/sync-codex-adapters.py; do not edit by hand.",
            f"name = {_toml_string(name)}",
            f"description = {_toml_string(description)}",
            f"sandbox_mode = {_toml_string(_sandbox_for_tools(tools))}",
            f"developer_instructions = {_toml_multiline(instructions)}",
            "",
        ]
    )
    return REPO / ".codex" / "agents" / f"{name}.toml", content


def _insert_after_frontmatter(text: str, note: str) -> str:
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise ValueError("missing frontmatter")
    return text[: match.end()] + note + text[match.end() :]


def _skill_adapter(path: Path) -> tuple[Path, str]:
    fields, _, text = _frontmatter_and_body(path)
    name = fields.get("name")
    if not name:
        raise ValueError(f"skill frontmatter lacks name: {path.relative_to(REPO)}")
    note = (
        f"> Codex adapter: generated from `{path.relative_to(REPO)}`. "
        "Do not edit this copy by hand; run `python scripts/sync-codex-adapters.py`.\n\n"
    )
    return REPO / ".agents" / "skills" / name / "SKILL.md", _insert_after_frontmatter(text, note)


def _command_skill_adapter(path: Path) -> tuple[Path, str]:
    fields, body, _ = _frontmatter_and_body(path)
    command_name = path.stem
    skill_name = f"command-{command_name}"
    description = fields.get("description", f"Codex adapter for Claude slash command /{command_name}")
    adapter_description = (
        f"Codex adapter for Claude slash command /{command_name} - {description}"
    )
    content = f"""---
name: {skill_name}
description: {_toml_string(adapter_description)}
---

# {skill_name}

Codex does not load project `.claude/commands/*.md` files as custom slash commands.
Use this skill when you would have used `/{command_name}` in Claude Code.

Canonical source: `{path.relative_to(REPO)}`. Do not edit this adapter by hand; edit the
Claude command and run `python scripts/sync-codex-adapters.py`.

{body.rstrip()}
"""
    return REPO / ".agents" / "skills" / skill_name / "SKILL.md", content


def expected_files() -> dict[Path, str]:
    expected: dict[Path, str] = {}
    for agent in sorted((REPO / ".claude" / "agents").glob("*.md")):
        path, content = _agent_adapter(agent)
        expected[path] = content
    for skill in sorted((REPO / ".claude" / "skills").glob("*/SKILL.md")):
        path, content = _skill_adapter(skill)
        expected[path] = content
    for command in sorted((REPO / ".claude" / "commands").glob("*.md")):
        path, content = _command_skill_adapter(command)
        expected[path] = content
    return expected


def expected_relpaths() -> set[str]:
    """The generated adapter set, expressed in manifest-compatible paths."""
    return {path.relative_to(REPO).as_posix() for path in expected_files()}


def _template_sync_module():
    """Load the production manifest classifier; do not duplicate its glob rules."""
    path = REPO / "scripts" / "template-sync.py"
    spec = importlib.util.spec_from_file_location("_template_sync_manifest", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("无法加载 scripts/template-sync.py 的 manifest classifier")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def generated_manifest_relpaths() -> set[str]:
    """Return tracked paths classified generated by the canonical manifest parser."""
    manifest = REPO / "template-manifest.toml"
    if not manifest.is_file():
        raise RuntimeError("缺少 template-manifest.toml")
    try:
        tracked = subprocess.run(
            ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.splitlines()
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(f"无法读取 tracked paths：{exc}") from exc
    try:
        rules = tomllib.loads(manifest.read_text(encoding="utf-8")).get("rule", [])
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise RuntimeError(f"无法解析 template-manifest.toml：{exc}") from exc
    classifier = _template_sync_module()
    return {rel for rel in tracked if classifier.classify(rel, rules) == "generated"}


def generated_manifest_errors() -> list[str]:
    """Enforce #61's exact generated-set contract for all tracked adapter paths."""
    try:
        declared = generated_manifest_relpaths()
    except RuntimeError as exc:
        return [f"无法校验 generated manifest 集合：{exc}"]
    expected = expected_relpaths()
    if declared == expected:
        return []
    return [
        "generated manifest 集合与 sync-codex-adapters.expected_files() 不一致："
        f"missing={sorted(expected - declared)} unexpected={sorted(declared - expected)}"
    ]


def existing_adapter_files() -> set[Path]:
    files: set[Path] = set()
    files.update((REPO / ".codex" / "agents").glob("*.toml"))
    files.update((REPO / ".agents" / "skills").glob("*/SKILL.md"))
    return files


def check() -> int:
    expected = expected_files()
    actual = existing_adapter_files()
    failures = generated_manifest_errors()
    for path, content in sorted(expected.items()):
        if not path.exists():
            failures.append(f"missing generated adapter: {path.relative_to(REPO)}")
            continue
        if path.read_text(encoding="utf-8", errors="replace") != content:
            failures.append(f"stale generated adapter: {path.relative_to(REPO)}")
    for path in sorted(actual - set(expected)):
        failures.append(f"unexpected generated adapter: {path.relative_to(REPO)}")

    for failure in failures:
        print(f"ERROR {failure}")
    status = "FAIL" if failures else "OK"
    print(f"[sync-codex-adapters] {status} — {len(failures)} issue(s)")
    return 1 if failures else 0


def write() -> int:
    expected = expected_files()
    for path, content in sorted(expected.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8", errors="replace") != content:
            path.write_text(content, encoding="utf-8")
    for path in sorted(existing_adapter_files() - set(expected)):
        path.unlink()
    print(f"[sync-codex-adapters] wrote {len(expected)} adapter file(s)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check adapters without writing")
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    sys.exit(main())
